# Generated by Django 5.2.16 on 2026-07-20 15:08

import django.db.models.deletion
import django.utils.timezone
import reporter.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("site", models.CharField(default="default", max_length=255)),
                ("group", models.CharField(default="default", max_length=255)),
                ("category", models.CharField(default="default", max_length=255)),
                ("url", models.TextField()),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                ("wait_for_selector", models.CharField(blank=True, max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["site", "group", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="GrafanaConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField()),
                ("login_path", models.CharField(default="/login", max_length=255)),
                ("username_ciphertext", models.TextField(blank=True)),
                ("password_ciphertext", models.TextField(blank=True)),
                (
                    "org_id",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                ("theme", models.CharField(default="dark", max_length=16)),
                ("kiosk", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="Asia/Jakarta", max_length=64)),
                ("viewport_width", models.PositiveIntegerField(default=3440)),
                ("viewport_height", models.PositiveIntegerField(default=1220)),
                ("full_page", models.BooleanField(default=True)),
                ("wait_seconds", models.PositiveIntegerField(default=8)),
                ("navigation_timeout_seconds", models.PositiveIntegerField(default=90)),
                ("panel_timeout_seconds", models.PositiveIntegerField(default=60)),
                ("ignore_https_errors", models.BooleanField(default=False)),
                (
                    "wait_for_selector",
                    models.CharField(
                        blank=True,
                        default=".panel-container, [data-testid='panel-container'], [data-testid='data-testid Panel header']",
                        max_length=500,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", reporter.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("weekly", "Weekly")],
                        max_length=16,
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            (
                                "previous_month_all",
                                "Previous month: weekly blocks and monthly",
                            ),
                            ("previous_month", "Previous month: monthly only"),
                            ("previous_7_days", "Previous 7 days"),
                        ],
                        max_length=32,
                    ),
                ),
                ("monthly_day", models.PositiveSmallIntegerField(default=1)),
                ("weekly_day", models.PositiveSmallIntegerField(default=0)),
                ("run_time", models.TimeField()),
                ("timezone", models.CharField(default="Asia/Jakarta", max_length=64)),
                ("all_dashboards", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dashboards",
                    models.ManyToManyField(
                        blank=True, related_name="schedules", to="reporter.dashboard"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("preset", models.CharField(max_length=32)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("folder_year", models.PositiveIntegerField()),
                ("folder_month", models.PositiveSmallIntegerField()),
                ("custom_filename", models.CharField(blank=True, max_length=255)),
                ("total_artifacts", models.PositiveIntegerField(default=0)),
                ("completed_artifacts", models.PositiveIntegerField(default=0)),
                ("failed_artifacts", models.PositiveIntegerField(default=0)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="reporter.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dashboard_name", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                ("group", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("dashboard_url", models.TextField()),
                ("dashboard_query_params", models.JSONField(blank=True, default=dict)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                ("wait_for_selector", models.CharField(blank=True, max_length=500)),
                ("report_type", models.CharField(max_length=16)),
                ("filename", models.CharField(max_length=255)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("folder_year", models.PositiveIntegerField()),
                ("folder_month", models.PositiveSmallIntegerField()),
                ("relative_path", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("capturing", "Capturing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("superseded", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reporter.dashboard",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="reporter.reportrun",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "site",
                    "group",
                    "category",
                    "dashboard_name",
                    "period_start",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "run",
                            "dashboard_name",
                            "filename",
                            "period_start",
                            "period_end",
                        ),
                        name="unique_run_artifact",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reportrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("schedule__isnull", False), ("scheduled_for__isnull", False)
                ),
                fields=("schedule", "scheduled_for"),
                name="unique_schedule_dispatch",
            ),
        ),
    ]
