# Generated by Django 5.2.16 on 2026-07-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="weekly_day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=0,
            ),
        ),
    ]
